DROP TABLE BOARD_IMG;
DROP TABLE BOARD;
--DROP TABLE MEMBER;

--DROP SEQUENCE SEQ_MEMBER_NO;
DROP SEQUENCE SEQ_BOARD_NO;
DROP SEQUENCE SEQ_BOARD_IMG_NO;

-- CREATE TABLE MEMBER(
--     USER_NO NUMBER PRIMARY KEY,
--     USER_NAME VARCHAR2(20) NOT NULL,
--     PROFILE_IMG VARCHAR2(100) NOT NULL
-- );

-- CREATE SEQUENCE SEQ_MEMBER_NO;
-- INSERT INTO MEMBER VALUES (SEQ_MEMBER_NO.NEXTVAL, 'KH 수달' , '/resources/images/sudal.PNG');
-- INSERT INTO MEMBER VALUES (SEQ_MEMBER_NO.NEXTVAL, 'KH 루피1' , '/resources/images/user0.jpg');
-- INSERT INTO MEMBER VALUES (SEQ_MEMBER_NO.NEXTVAL, 'KH 루피2' , '/resources/images/user1.jpg');
-- INSERT INTO MEMBER VALUES (SEQ_MEMBER_NO.NEXTVAL, 'KH 루피3' , '/resources/images/user2.jpg');
-- INSERT INTO MEMBER VALUES (SEQ_MEMBER_NO.NEXTVAL, 'KH 루피4' , '/resources/images/user3.jpg');
-- INSERT INTO MEMBER VALUES (SEQ_MEMBER_NO.NEXTVAL, 'KH 루피5' , '/resources/images/user4.jpg');
-- INSERT INTO MEMBER VALUES (SEQ_MEMBER_NO.NEXTVAL, 'KH 루피6' , '/resources/images/user5.jpg');

-- COMMIT;

CREATE TABLE BOARD(
    NO NUMBER PRIMARY KEY,
    TITLE VARCHAR2(400) NOT NULL,
    SUB_TITLE VARCHAR2(200) ,
    CONTENT VARCHAR2(4000) NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE
   -- ,USER_NO NUMBER REFERENCES MEMBER
);

CREATE TABLE BOARD_IMG(
    BOARD_IMG_NO NUMBER PRIMARY KEY,
    UPLOAD_PATH VARCHAR2(200) NOT NULL,
    ORIGIN_NAME VARCHAR2(200) NOT NULL,
    CHANGE_NAME VARCHAR2(200) NOT NULL,
    REF_NO NUMBER REFERENCES BOARD
);

CREATE SEQUENCE SEQ_BOARD_NO;

CREATE SEQUENCE SEQ_BOARD_IMG_NO;
